---
# only needed for readthedocs.io
site_name: 'Free Templates for AWS CloudFormation'
docs_dir: docs
pages:
- 'Home': 'index.md'
- 'EC2': 'ec2.md'
- 'ECS': 'ecs.md'
- 'Jenkins': 'jenkins.md'
- 'Operations': 'operations.md'
- 'Security': 'security.md'
- 'State / Data': 'state.md'
- 'Static Website': 'static-website.md'
- 'VPC': 'vpc.md'
- 'WordPress': 'wordpress.md'
- 'widdix CLI': 'cli.md'
- 'Migrate to v8': 'migrate-v8.md'
