---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static Website: Index document support in subdirectories, a cloudonaut.io template'
Parameters:
  IndexDocument:
    Description: 'The name of the index document for the website.'
    Type: String
    Default: 'index.html'
Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'lambda.amazonaws.com'
            - 'edgelambda.amazonaws.com'
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        # If you change the ZipFile, rename the logical id LambdaVersionV1 to trigger a new version creation!
        ZipFile: !Sub |
          'use strict';
          const regex = /\.[a-z]*$/;
          exports.handler = (event, context, cb) => {
            console.log(`Invoke: ${!JSON.stringify(event)}`);
            const request = event.Records[0].cf.request;
            if (request.uri.endsWith('/')) {
              request.uri += '${IndexDocument}';
            } else if (!regex.test(request.uri)) {
              request.uri += '/${IndexDocument}';
            }
            cb(null, request);
          };
      Handler: 'index.handler'
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: 'nodejs6.10'
      Timeout: 10
  LambdaVersionV1:
    Type: 'AWS::Lambda::Version'
    Properties:
      FunctionName: !Ref LambdaFunction
Outputs:
  TemplateID:
    Description: 'cloudonaut.io template id.'
    Value: 'static-website/lambdaedge-index-document'
  TemplateVersion:
    Description: 'cloudonaut.io template version.'
    Value: '__VERSION__'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  LambdaVersionArn:
    Description: 'Version ARN of Lambda@Edge function.'
    Value: !Ref LambdaVersionV1
